[profile.default]
solc = '0.8.23'
vm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 100000000
block_number = 14126430
block_timestamp = 1643802347
runs = 16384
libs = ["node_modules", "lib"]
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
ethereum ="${RPC_ETHEREUM_MAINNET}"
optimism = "${RPC_OPTIMISM_MAINNET}"
polygon = "${RPC_POLYGON_MUMBAI}"
arbitrum = "${RPC_ARBITRUM_MAINNET}"
base = "${RPC_BASE_MAINNET}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
ethereum_sepolia ="${RPC_ETHEREUM_SEPOLIA}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
polygon_mumbai = "${RPC_POLYGON_MUMBAI}"
base_sepolia = "${RPC_BASE_SEPOLIA}"

[profile.fork] # run via FOUNDRY_PROFILE=fork foundry test

[profile.ci_sizes]
optimizer_runs = 200

[invariant] 
fail_on_revert = false

[fuzz]
runs = 16384
seed = '0xd70284f7'
include_storage = true
include_push_bytes = true

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
